# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6c75a835a41089f4b84b77579bf7a5e"
application_url = "https://cultures-summer-tags-circle.trycloudflare.com"
embedded = true
name = "ANOTAI"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "products/create", "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://cultures-summer-tags-circle.trycloudflare.com/auth/callback", "https://cultures-summer-tags-circle.trycloudflare.com/auth/shopify/callback", "https://cultures-summer-tags-circle.trycloudflare.com/api/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "/api/chat"
subpath = "chat"
prefix = "apps"
