# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6c75a835a41089f4b84b77579bf7a5e"
application_url = "https://b7d3a9cbfbe51f.lhr.life"
embedded = true
name = "ANOTAI"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_discounts"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "carts/update", "orders/create", "products/create", "products/update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/privacy"

[auth]
redirect_urls = [ "https://b7d3a9cbfbe51f.lhr.life/auth/callback", "https://b7d3a9cbfbe51f.lhr.life/auth/shopify/callback", "https://b7d3a9cbfbe51f.lhr.life/api/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
